os: 
  - Visual Studio 2015
  - Visual Studio 2013

platform:
  - Win32
  - Win64

before_build:
  - ps: Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/xmake-io/xmake/master/scripts/get.ps1' -UseBasicParsing).Content
  - cmd: xmake --version

build_script:
  - cmd: xmake
  - cmd: xmake p
  - cmd: if %platform%==Win32 xmake f -m debug
  - cmd: if %platform%==Win64 xmake f -m debug -a x64
  - cmd: xmake -r

test_script:
  - cmd: xmake r demo
